### ISSUE TITLE
Histogram / Summary Sum should be a gauge

### ISSUE THREAD

**Issue by belm0** [OpenObservability/OpenMetrics#188] opened 2021-02-26 06:01 UTC
why:
  * histograms and averages supporting negative observations are desirable
  * it should be possible to trivially derive mean from a Histogram

Where is the documented rationale for Sum being of type counter rather than a gauge?  Not supporting negative observations is a significant loss, so it would have to be very compelling.

If Sum is not a gauge, as a user I'm forced to add my own gauge sum metric along side every Histogram and Summary instance.

> Semantically, Sum, and buckets values are counters so MUST NOT be NaN or negative. Negative threshold buckets MAY be used, but then the Histogram MetricPoint MUST NOT contain a sum value as it would no longer be a counter semantically.

**Comment by belm0** [comment] 2021-02-26 06:30
in Python prometheus_client I found there is a "gaugehistogram" type added

  * it adds incompatible `_gcount` an `_gsum` child metrics
  * why `_gcount`?  The count is still monotonically increasing.
  * why make two types and make all levels of prometheus (client, server, queries, etc.) care about it?
  * it doesn't address Summary, which should also support negative observations

**Comment by brian-brazil** [comment] 2021-02-26 08:24
This behaviour has been discussed at length, and this is an explicit design decision. Allowing counters to go backwards would break all existing monitoring systems we're aware of, as none of them would then be able to calculate the correct rate for the _sum  and thus would not be able to calculate any rates or subsequently averages.

Closing as duplicate of #143.

> in Python prometheus_client I found there is a "gaugehistogram" type added

This is not related to your question. Gcount does not monotonically increase, it is a gauge which can go up or down from scrape to scrape.

**Closed by brian-brazil** 2021-02-26 08:24 UTC

**Comment by belm0** [comment] 2021-02-26 08:30
I read https://github.com/OpenObservability/OpenMetrics/issues/64

It's straightforward to agree that `_mean` is not a useful metric.

But that is besides the point of `_sum` being a gauge or counter.  If it's a gauge, there is no precision issue, and together with `_count` it's possible to compute the average at every point it time.

**Comment by brian-brazil** [comment] 2021-02-26 08:41
We aim to work with what monitoring systems are actually out there, and build on the install base that Prometheus and its format have rather than inventing brand new things that no one currently supports or has experience with. For what you'd suggest we'd have to get the capability to handled this added to all monitoring systems out these including Prometheus, Graphite, and the various SaaS vendors for the sake of what is as far as we're aware an extremely rare use case. Put another way it doesn't make sense to break the ability to calculate the average for the ~99.9% of users where it is a counter and observations are always positive for the sake of the ~0.1% of uses where there might be a case for negative observations.

If you need this, I'd suggest having two counters - one for the ups and one for the downs. It is not an aim of OpenMetrics to have a first-class metric type for every possible use case, rather allowing users to combine Counters/Gauges as needed. There's no position metric type either for example, as two gauges for longitude and latitude can handle that.
